// Generated by scripts/generate-maps.mjs. Edit maps.config.json, not this file.
export type MapItem = {
  id: string;
  group: string;
  title: string;
  original: string;
  preview: string;
  thumbnail: string;
  width: number;
  height: number;
};

export const maps: MapItem[] = [
  { id: "ground-zero-3d", group: "中心区", title: "中心区 3D", original: "./中心区3D_ground-zero-3d.png", preview: "./previews/ground-zero-3d.webp", thumbnail: "./thumbs/ground-zero-3d.webp", width: 2656, height: 2160 },
  { id: "ground-zero-2d", group: "中心区", title: "中心区 2D", original: "./中心区2D_ground-zero-2d.png", preview: "./previews/ground-zero-2d.webp", thumbnail: "./thumbs/ground-zero-2d.webp", width: 4096, height: 4096 },
  { id: "customs-3d", group: "海关", title: "海关 3D", original: "./海关3D_customs-3d.jpg", preview: "./previews/customs-3d.webp", thumbnail: "./thumbs/customs-3d.webp", width: 6395, height: 4096 },
  { id: "factory-3d", group: "工厂", title: "工厂 3D", original: "./工厂3D_factory-3d.jpg", preview: "./previews/factory-3d.webp", thumbnail: "./thumbs/factory-3d.webp", width: 13440, height: 6656 },
  { id: "woods-3d", group: "森林", title: "森林 3D", original: "./森林3D_woods-3d.jpg", preview: "./previews/woods-3d.webp", thumbnail: "./thumbs/woods-3d.webp", width: 7680, height: 5168 },
  { id: "interchange-3d", group: "立交桥", title: "立交桥 3D", original: "./立交桥3D_interchange-3d.jpg", preview: "./previews/interchange-3d.webp", thumbnail: "./thumbs/interchange-3d.webp", width: 9600, height: 5400 },
  { id: "interchange-ultra-3d", group: "立交桥", title: "立交桥－商场 3D", original: "./立交桥-商场3D_interchange-ultra-3d.png", preview: "./previews/interchange-ultra-3d.webp", thumbnail: "./thumbs/interchange-ultra-3d.webp", width: 6121, height: 4190 },
  { id: "shoreline-3d", group: "海岸线", title: "海岸线 3D", original: "./海岸线3D_shoreline-3d.jpg", preview: "./previews/shoreline-3d.webp", thumbnail: "./thumbs/shoreline-3d.webp", width: 5760, height: 3240 },
  { id: "shoreline-resort", group: "海岸线", title: "海岸线－疗养院内部", original: "./海岸线-疗养院内部_shoreline-resort.png", preview: "./previews/shoreline-resort.webp", thumbnail: "./thumbs/shoreline-resort.webp", width: 5095, height: 5167 },
  { id: "reserve-3d", group: "储备站", title: "储备站 3D", original: "./储备站3D_reserve-3d.jpg", preview: "./previews/reserve-3d.webp", thumbnail: "./thumbs/reserve-3d.webp", width: 5760, height: 3240 },
  { id: "reserve-tunnels-3d", group: "储备站", title: "储备站－地下通道 3D", original: "./储备站-地下通道3D_reserve-tunnels-3d.png", preview: "./previews/reserve-tunnels-3d.webp", thumbnail: "./thumbs/reserve-tunnels-3d.webp", width: 3240, height: 5760 },
  { id: "lighthouse-vert-3d", group: "灯塔", title: "灯塔（垂直地图）3D", original: "./灯塔（垂直地图）3D_lighthouse-vert-3d.png", preview: "./previews/lighthouse-vert-3d.webp", thumbnail: "./thumbs/lighthouse-vert-3d.webp", width: 4130, height: 3780 },
  { id: "lighthouse-iso-3d", group: "灯塔", title: "灯塔（水平地图）3D", original: "./灯塔（水平地图）3D_lighthouse-iso-3d.png", preview: "./previews/lighthouse-iso-3d.webp", thumbnail: "./thumbs/lighthouse-iso-3d.webp", width: 5856, height: 3780 },
  { id: "streets-of-tarkov-3d", group: "街区", title: "街区 3D", original: "./街区3D_streets-of-tarkov-3d.jpg", preview: "./previews/streets-of-tarkov-3d.webp", thumbnail: "./thumbs/streets-of-tarkov-3d.webp", width: 7605, height: 4841 },
  { id: "streets-of-tarkov-lexos-minefield", group: "街区", title: "街区 4S 店雷区", original: "./街区4S店雷区_streets-of-tarkov-lexos-minefield.png", preview: "./previews/streets-of-tarkov-lexos-minefield.webp", thumbnail: "./thumbs/streets-of-tarkov-lexos-minefield.webp", width: 3832, height: 4920 },
  { id: "labyrinth-3d", group: "迷宫", title: "迷宫 3D", original: "./迷宫3D_labyrinth-3d.png", preview: "./previews/labyrinth-3d.webp", thumbnail: "./thumbs/labyrinth-3d.webp", width: 4040, height: 3840 },
  { id: "labs", group: "实验室", title: "实验室", original: "./实验室_labs.png", preview: "./previews/labs.webp", thumbnail: "./thumbs/labs.webp", width: 3000, height: 1555 },
];
